[package]
name = "rust_udp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "udp_receiver"
path = "src/udp_receiver.rs"

[[bin]]
name = "udp_sender"
path = "src/udp_sender.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
